name: GitHub Actions Demo

on: [push]

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: |
          echo "Hello world 🎉 "
      - name: exmaple this will fail
        run: exit 1;
      
      
